### ISSUE TITLE
No Project Proposal

### ISSUE THREAD

**Issue by ratnanil** [nikitakrahenbuhl/datachallenge-n#1]
Hey Nikita

Yesterday was the due date for the proposal of your project in the course Computational Movement Analysis. You should have updated the topics addressed in the [Readme](https://github.com/nikitakrahenbuhl/datachallenge-n/blob/master/Readme.md) file.  You haven't done this yet... What was the issue? Where did you save your project proposal?

Cheers,

Nils

**Comment by nikitakrahenbuhl** [comment]
Hi Nils,

Noted and replied per email. I will update this repo with my proposal tonight and notify you by resolving the issue.

**Comment by nikitakrahenbuhl** [comment]
Hi @ratnanil,

I have since added my project proposal text. I still need to add some theory to the concept this evening but I reckon this should help us have a productive coaching section.
